# Site settings
title:          Katrina M. Wehr
description:    "My personal website"

url:            "https://kat-wehr.github.io/mysite"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Katrina Wehr
  url:          https://katrinawehr.com
  email:        katrina.m.wehr@gmail.com

# Social 
twitter_username:     katrinamwehr
github_username:      kat-wehr
linkedin_username:    katmwehr

# Build settings
markdown:       kramdown
include:
  - _pages
  - _portfolio

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
